# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.ollama_service_url: 'http://127.0.0.1:11434' # Default value, should be overridden by .env
    # app.ollama_service_url: 'http://127.0.0.1:11444' # Default value, should be overridden by .env
    # app.ollama_service_url: 'http://192.168.128.44:11434' # Default value, should be overridden by .env
    app.ollama_temperature: 1
    app.ollama_num_ctx: 4096
    app.ollama_top_k: 40
    app.ollama_top_p: 0.9
    app.files_dir: 'var/files'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    'App\Service\FilePathGenerator':
        arguments:
            $projectRoot: '%kernel.project_dir%'
            $basePathRelative: '%app.files_dir%'

    'App\Service\OllamaService':
        arguments:
            $ollamaServiceUrl: '%app.ollama_service_url%'
            $temperature: '%app.ollama_temperature%'
            $numCtx: '%app.ollama_num_ctx%'
            $topK: '%app.ollama_top_k%'
            $topP: '%app.ollama_top_p%'

when@test:
    parameters:
        app.files_dir: 'var/files_test'
